#!/bin/sh

echo "Running static analysis..."

# Inspect code using Ktlint
./gradlew ktlint > analysis_output.log 2>&1
status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo 1>&2 "ERROR: Static analysis found violations."
    read -p "Auto fix them by ktlintFormat? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
        ./gradlew ktlintFormat ktlint > analysis_output.log 2>&1
        status=$?

        if [ "$status" -ne 0 ]; then
        echo 1>&2 "Error persist. Try to fix manually. See more at file 'analysis_output.log'"
        exit 1
        fi
    else 
        echo 1>&2 "Fix errors manually. See more at file 'analysis_output.log'"
        exit 1
    fi
fi