#!/bin/sh

NUM_CHANGES="$(git status --porcelain | wc -l)"

if [[  $NUM_CHANGES -gt 0 ]]; then 
    echo "Running static analysis..."

    # Inspect code using Ktlint
    ./gradlew ktlint > analysis_output.log 2>&1
    status=$?

    if [ "$status" = 0 ] ; then
        echo "STATIC ANALYSIS SUCCESSFUL in $SECONDS s."
        exit 0
    else
        echo 1>&2 "ERROR: Static analysis found violations."
        read -p "Auto fix them by ktlintFormat? [y|n] " -n 1 -r < /dev/tty
        echo
        if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
            ./gradlew ktlintFormat ktlint > analysis_output.log 2>&1
            status=$?

            if [ "$status" -ne 0 ]; then
                echo 1>&2 "ERROR: Try to fix manually. See more at file 'analysis_output.log'"
                exit 1
            else
                echo "FORMAT SUCCESSFUL in $SECONDS s."
            fi
        else 
            echo 1>&2 "ERROR: Fix errors manually. See more at file 'analysis_output.log'"
            exit 1
        fi
    fi

    exit 0
fi